<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktiver';
$labels['twofactor_gauthenticator'] = '2-trins verificering';
$labels['code'] = 'Autentificering kode';

$labels['two_step_verification_form'] = '2-trins verificering';

$labels['secret'] = 'Hemmelig kode';
$labels['qr_code'] = 'QR kode';
$labels['msg_infor'] = 'Du kan scanne denne QR kode med en TOTP kompatibel app som for eksempel <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>).';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Brugervejledning</a>';

$labels['show_secret'] = 'Vis hemmelig kode';
$labels['hide_secret'] = 'Skjul hemmelig kode';
$labels['create_secret'] = 'Generer hemmelig kode';

$labels['show_qr_code'] = 'Vis QR kode';
$labels['hide_qr_code'] = 'Skjul QR kode';

$labels['recovery_codes'] = 'Genopretnings koder';
$labels['show_recovery_codes'] = 'Vis genopretnings koder';
$labels['hide_recovery_codes'] = 'Skjul  genopretnings koder';

$labels['setup_all_fields'] = 'Opret alle felter (behøver Gem)';

$labels['enrollment_dialog_title'] = '2-trins OTP verificering';
$labels['enrollment_dialog_msg'] = '<strong>2-trins OTP verificerings koder</strong> er påkrævet for sikkerhed, konfigurer venligst';

$labels['check_code'] = 'Kontroller kode';
$labels['code_ok'] = 'Koden er OK';
$labels['code_ko'] = 'Koden er forkert';

$labels['dont_ask_me_30days'] = 'Spørg mig ikke igen de næste 30 dage på denne computer';

$labels['check_code_to_activate'] = 'For at gemme, scan QR koden og indtast verificeringskoden nederst.';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Gemt succesefuldt.';
