<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktivieren';
$labels['twofactor_gauthenticator'] = '2-Faktor Authentifizierung';
$labels['code'] = 'Google Authenticator Code';

$labels['two_step_verification_form'] = '2-Faktor Best&auml;tigungscode';

$labels['secret'] = 'Secret';
$labels['qr_code'] = 'QR Code';
$labels['msg_infor'] = 'Sie k&ouml;nnen mit dem <a href="https://github.com/google/google-authenticator" target="_blank">Google-Authenticator</a> ein Secret erstellen und dieses benutzen.';

$labels['show_secret'] = 'Zeige Secret';
$labels['hide_secret'] = 'Verstecke Secret';
$labels['create_secret'] = 'Erstelle Secret';

$labels['show_qr_code'] = 'Zeige QR Code';
$labels['hide_qr_code'] = 'Verstecke QR Code';

$labels['recovery_codes'] = 'Wiederherstellungscodes';
$labels['show_recovery_codes'] = 'Zeige Wiederherstellungscodes';
$labels['hide_recovery_codes'] = 'Verstecke Wiederherstellungscodes';

$labels['setup_all_fields'] = 'Setup all fields (needs Save)';

$labels['enrollment_dialog_title'] = '2-Faktor Authentifizierung';
$labels['enrollment_dialog_msg'] = '<strong>2-Faktor Authentifizierung Best&auml;tigungscodes</strong> werden aus Sicherheitsgr&uuml;nden ben&ouml;tigt, bitte konfigurieren!';

$labels['check_code'] = '&Uuml;berpr&uuml;fe Code';
$labels['code_ok'] = 'Code OK';
$labels['code_ko'] = 'Falscher Code';

$labels['dont_ask_me_30days'] = 'Don\'t ask me codes again on this computer for 30 days';

$labels['check_code_to_activate'] = 'To save, you need to check any code before';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Konfiguration erfolgreich gespeichert.';
