<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktivieren';
$labels['twofactor_gauthenticator'] = 'Zwei-Faktor-Authentifizierung';
$labels['code'] = 'Google-Authenticator-Code';

$labels['two_step_verification_form'] = 'Zwei-Faktor-Bestätigungscode';

$labels['secret'] = 'Secret';
$labels['qr_code'] = 'QR-Code';
$labels['msg_infor'] = 'Sie können mit jeder TOTP kompatiblen App wie z.B. <a href="https://github.com/google/google-authenticator" target="_blank">Google-Authenticator</a> ein Secret erstellen und dieses verwenden.';

$labels['show_secret'] = 'Zeige Secret';
$labels['hide_secret'] = 'Verstecke Secret';
$labels['create_secret'] = 'Erstelle Secret';

$labels['show_qr_code'] = 'Zeige QR-Code';
$labels['hide_qr_code'] = 'Verstecke QR-Code';

$labels['recovery_codes'] = 'Wiederherstellungscodes';
$labels['show_recovery_codes'] = 'Zeige Wiederherstellungscodes';
$labels['hide_recovery_codes'] = 'Verstecke Wiederherstellungscodes';

$labels['setup_all_fields'] = 'Erstelle fehlende Werte (Speichern klicken, um Ihre Einstellungen zu sichern)';

$labels['enrollment_dialog_title'] = 'Zwei-Faktor-Authentifizierung';
$labels['enrollment_dialog_msg'] = '<strong>Bestätigungscodes für Zwei-Faktor-Authentifizierung</strong> werden aus Sicherheitsgründen benötigt, bitte konfigurieren!';

$labels['check_code'] = 'Überprüfe Code';
$labels['code_ok'] = 'Code OK';
$labels['code_ko'] = 'Falscher Code';

$labels['dont_ask_me_30days'] = 'Nicht erneut nach dem Code fragen für die nächsten 30 Tage';

$labels['check_code_to_activate'] = 'Um zu speichern, muss mindestens 1 Code zuvor geprüft werden';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Konfiguration erfolgreich gespeichert.';
