<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activate';
$labels['twofactor_gauthenticator'] = '2steps Google verification';
$labels['code'] = 'Google Authenticator Code';

$labels['two_step_verification_form'] = '2-Step Verification';

$labels['secret'] = 'Secret';
$labels['qr_code'] = 'QR Code';
$labels['msg_infor'] = 'You can add a <i>secret</i> generated with <a href="https://code.google.com/p/google-authenticator/" target="_blank">google-authenticator</a> and use that';

$labels['show_secret'] = 'Show secret';
$labels['hide_secret'] = 'Hide secret';
$labels['create_secret'] = 'Create secret';

$labels['show_qr_code'] = 'Show QR Code';
$labels['hide_qr_code'] = 'Hide QR Code';

$labels['recovery_codes'] = 'Recovery codes';
$labels['show_recovery_codes'] = 'Show recovery codes';
$labels['hide_recovery_codes'] = 'Hide recovery codes';

$labels['setup_all_fields'] = 'Setup all fields (needs Save)';

$labels['enrollment_dialog_title'] = '2steps Google verification';
$labels['enrollment_dialog_msg'] = '<strong>2-steps verification codes</strong> are required for safety, please config';

$labels['check_code'] = 'Check code';
$labels['code_ok'] = 'Code OK';
$labels['code_ko'] = 'Incorrect code';

$labels['dont_ask_me_30days'] = 'Don\'t ask me codes again on this computer for 30 days';

$labels['check_code_to_activate'] = 'To save, you need to check any code before';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Configuration are saved successfully.';
?>
