<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activar';
$labels['twofactor_gauthenticator'] = 'Verificación de Google de dos pasos';
$labels['code'] = 'Código de autenticación';

$labels['two_step_verification_form'] = 'Verificación de dos pasos';

$labels['secret'] = 'Secreto';
$labels['qr_code'] = 'Código QR';
$labels['msg_infor'] = 'Podés agregar una <em>clave</em> generada con <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) o <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a>';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Manual del usuario</a>';

$labels['show_secret'] = 'Mostrar clave';
$labels['hide_secret'] = 'Ocultar clave';
$labels['create_secret'] = 'Generar nueva clave';

$labels['show_qr_code'] = 'Mostrar código QR';
$labels['hide_qr_code'] = 'Ocultar código QR';

$labels['recovery_codes'] = 'Códigos de recuperación';
$labels['show_recovery_codes'] = 'Mostrar códigos de recuperación';
$labels['hide_recovery_codes'] = 'Ocultar códigos de recuperación';

$labels['setup_all_fields'] = 'Configurar todos los campos (requiere guardar)';

$labels['enrollment_dialog_title'] = 'Verificación de Google de dos pasos';
$labels['enrollment_dialog_msg'] = 'Los <strong>códigos de autenticación de dos pasos</strong> se requieren por seguridad. Por favor configurar.';

$labels['check_code'] = 'Comprobar código';
$labels['code_ok'] = 'Código correcto';
$labels['code_ko'] = 'Código incorrecto';

$labels['dont_ask_me_30days'] = 'No solicitar códigos en esta computadora durante 30 días';

$labels['check_code_to_activate'] = 'Para poder guardar, antes debe de chequearse algún código';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Configuración guardada exitosamente';

