<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activar';
$labels['twofactor_gauthenticator'] = '2steps Google verification';
$labels['code'] = 'Google Authenticator Code';

$labels['two_step_verification_form'] = 'Verificación de dos pasos';

$labels['secret'] = 'Secreto';
$labels['qr_code'] = 'Código QR';
$labels['msg_infor'] = 'Puedes añadir un <i>secreto</i> generado en tu ordenador con <a href="https://code.google.com/p/google-authenticator/" target="_blank">google-authenticator</a> e usarlo';

$labels['show_secret'] = 'Ver secreto';
$labels['hide_secret'] = 'Esconder secreto';
$labels['create_secret'] = 'Crear secreto';

$labels['show_qr_code'] = 'Ver código QR';
$labels['hide_qr_code'] = 'Esconder código QR';

$labels['recovery_codes'] = 'Códigos de recuperación';
$labels['show_recovery_codes'] = 'Ver códigos de recuperación';
$labels['hide_recovery_codes'] = 'Esconder códigos de recuperación';

$labels['setup_all_fields'] = 'Configurar todos los campos (necesita Guardar)';

$labels['enrollment_dialog_title'] = '2steps Google verification';
$labels['enrollment_dialog_msg'] = 'Está activada la <strong>Verificación en dos pasos</strong> por seguridad, es obligatorio emplearla para autenticarse';

$labels['check_code'] = 'Comprobar código';
$labels['code_ok'] = 'Codigo correcto';
$labels['code_ko'] = 'Codigo erróneo';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Los datos han sido guardados correctamente.';
?>
