<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activar';
$labels['twofactor_gauthenticator'] = 'Doble factor de autenticación (2FA)';
$labels['code'] = 'Código de verificación';

$labels['two_step_verification_form'] = 'Doble factor de autenticación';

$labels['secret'] = 'Secreto';
$labels['qr_code'] = 'Código QR';
$labels['msg_infor'] = 'El código QR contiene las configuraciones de doble factor.<br>Puedes escanearlo utilizando una aplicación compatible con TOTP como <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">App Store</a>) o <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a>';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Manual del usuario</a>';

$labels['show_secret'] = 'Ver secreto';
$labels['hide_secret'] = 'Esconder secreto';
$labels['create_secret'] = 'Crear secreto';

$labels['show_qr_code'] = 'Ver código QR';
$labels['hide_qr_code'] = 'Esconder código QR';

$labels['recovery_codes'] = 'Códigos de recuperación';
$labels['show_recovery_codes'] = 'Ver códigos de recuperación';
$labels['hide_recovery_codes'] = 'Esconder códigos de recuperación';

$labels['setup_all_fields'] = 'Generar configuración';

$labels['enrollment_dialog_title'] = 'Active el doble factor de autenticación';
$labels['enrollment_dialog_msg'] = 'Para una mayor seguridad, el <strong>Doble Factor de Autenticación (2FA)</strong> está activo, por favor configúralo ahora';

$labels['check_code'] = 'Comprobar código';
$labels['code_ok'] = 'Código correcto';
$labels['code_ko'] = 'Código erróneo';

$labels['dont_ask_me_30days'] = 'No solicitar códigos en este dispositivo durante 30 días';

$labels['check_code_to_activate'] = 'Antes de guardar, escanea el código QR y comprueba que tu código 2FA funciona';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Los datos han sido guardados correctamente.';

