<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activar';
$labels['twofactor_gauthenticator'] = '2steps Google verification';
$labels['code'] = 'Google Authenticator Code';

$labels['secret'] = 'Secreto';
$labels['qr_code'] = 'Código QR';
$labels['msg_infor'] = 'Puedes añadir un <i>secreto</i> generado en tu ordenador con <a href="https://code.google.com/p/google-authenticator/" target="_blank">google-authenticator</a> e usarlo';

$labels['show_secret'] = 'Ver secreto';
$labels['hide_secret'] = 'Esconder secreto';
$labels['create_secret'] = 'Crear secreto';

$labels['show_qr_code'] = 'Ver código QR';
$labels['hide_qr_code'] = 'Esconder código QR';


// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Los datos han sido guardados correctamente.';
?>
