<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activer';
$labels['twofactor_gauthenticator'] = 'Authentification en 2 étapes';
$labels['code'] = 'Code d\'authentification';

$labels['two_step_verification_form'] = 'Vérification en 2 étapes';

$labels['secret'] = 'Secret';
$labels['qr_code'] = 'QR Code';
$labels['msg_infor'] = 'Vous pouvez scanner ce QR code avec une application compatible TOTP comme <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>).';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Manuel d\'utilisation</a>';

$labels['show_secret'] = 'Afficher le secret';
$labels['hide_secret'] = 'Masquer le secret';
$labels['create_secret'] = 'Créer un secret';

$labels['show_qr_code'] = 'Afficher le QR Code';
$labels['hide_qr_code'] = 'Masquer le QR Code';

$labels['recovery_codes'] = 'Codes de récupération';
$labels['show_recovery_codes'] = 'Afficher les codes de récupération';
$labels['hide_recovery_codes'] = 'Masquer les codes de récupération';

$labels['setup_all_fields'] = 'Configurer les champs (Enregistrement nécessaire)';

$labels['enrollment_dialog_title'] = 'Vérification OTP en 2 étapes';
$labels['enrollment_dialog_msg'] = 'Les <strong>codes de vérification en 2 étapes</strong> sont requis pour des raisons de sécurité, configurez-en SVP.';

$labels['check_code'] = 'Vérifier le code';
$labels['code_ok'] = 'Code OK';
$labels['code_ko'] = 'Code incorrect';

$labels['dont_ask_me_30days'] = 'Ne plus me demander de codes pour 30 jours.';

$labels['check_code_to_activate'] = 'Pour enregistrer, scannez le QR Code et entrez un premier code de vérification ci-dessous.';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Configuration sauvegardée.';

