<?php
// Labels used for different portions of the plugin
$labels = array();

$labels['activate'] = 'Activar';
$labels['twofactor_gauthenticator'] = '2steps Google verification';
$labels['code'] = 'Google Authenticator Code';

$labels['secret'] = 'Secreto';
$labels['qr_code'] = 'Código QR';
$labels['msg_infor'] = 'Podes engadir un <i>secreto</i> generado na tua computadora con <a href="https://code.google.com/p/google-authenticator/" target="_blank">google-authenticator</a> e empregalo';

$labels['show_secret'] = 'Ver secreto';
$labels['hide_secret'] = 'Agochar secreto';
$labels['create_secret'] = 'Crear secreto';

$labels['show_qr_code'] = 'Ver código QR';
$labels['hide_qr_code'] = 'Agochar código QR';

$labels['recovery_codes'] = 'Códigos de recuperación';
$labels['show_recovery_codes'] = 'Ver códigos de recuperación';
$labels['hide_recovery_codes'] = 'Agochar códigos de recuperación';


// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Os datos para a conta foron gardados correctamente.';

?>
