<?php
// Labels used for different portions of the plugin
$labels = array();

$labels['activate'] = 'Activar';
$labels['twofactor_gauthenticator'] = '2steps Google verification';
$labels['code'] = 'Google Authenticator Code';

$labels['two_step_verification_form'] = 'Verificación de dous pasos';

$labels['secret'] = 'Segredo';
$labels['qr_code'] = 'Código QR';
$labels['msg_infor'] = 'Podes engadir un <i>segredo</i> xerado na tua computadora con <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) o <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> e empregalo';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Manual do usuario</a>';

$labels['show_secret'] = 'Ver segredo';
$labels['hide_secret'] = 'Agochar segredo';
$labels['create_secret'] = 'Crear segredo';

$labels['show_qr_code'] = 'Ver código QR';
$labels['hide_qr_code'] = 'Agochar código QR';

$labels['recovery_codes'] = 'Códigos de recuperación';
$labels['show_recovery_codes'] = 'Ver códigos de recuperación';
$labels['hide_recovery_codes'] = 'Agochar códigos de recuperación';

$labels['setup_all_fields'] = 'Configurar tódolos campos (necesita Gardar)';

$labels['enrollment_dialog_title'] = '2steps Google verification';
$labels['enrollment_dialog_msg'] = 'Está activada a <strong>Verificación en dous pasos</strong> por seguridade, debese empregar obrigatoriamente. Faga o favor de configurala';

$labels['check_code'] = 'Comprobar código';
$labels['code_ok'] = 'Codigo correcto';
$labels['code_ko'] = 'Codigo erróneo';

$labels['dont_ask_me_30days'] = 'Non solicitar códigos nesta computadora durante 30 días';

$labels['check_code_to_activate'] = 'Para poder gardar, antes debese ter comprobado a validez dalgún código';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Os datos para a conta foron gardados correctamente.';

