<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktiválás';
$labels['twofactor_gauthenticator'] = 'Kétfaktoros bejelentkezés';
$labels['code'] = 'Hitelesítési kód';

$labels['two_step_verification_form'] = 'Kétfaktoros hitelesítő kód:';

$labels['secret'] = 'Titok';
$labels['qr_code'] = 'QR-kód';
$labels['msg_infor'] = 'Beolvashatja ezt a kétfaktoros beállításokat tartalmazó QR-kódot egy TOTP kompatibilis alkalmazással, mint pl. a <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) vagy <a href="https://github.com/google/google-authenticator" target="_blank">Google Hitelesítő</a>';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Felhasználói kézikönyv</a>';

$labels['show_secret'] = 'Titok mutatása';
$labels['hide_secret'] = 'Titok elrejtése';
$labels['create_secret'] = 'Titok készítése';

$labels['show_qr_code'] = 'QR-kód mutatása';
$labels['hide_qr_code'] = 'QR-kód elrejtése';

$labels['recovery_codes'] = 'Helyreállítási kódok';
$labels['show_recovery_codes'] = 'Helyreállítási kódok mutatása';
$labels['hide_recovery_codes'] = 'Helyreállítási kódok elrejtése';

$labels['setup_all_fields'] = 'Töltse ki az összes mezőt (feltétlenül kattintson a Mentés gombra a beállítások tárolásához)';

$labels['enrollment_dialog_title'] = 'Kétfaktoros hitelesítés regisztrációja';
$labels['enrollment_dialog_msg'] = '<strong>Kétfaktoros hitelesítő kód</strong> szükséges a biztonság növeléséhez, kérem állítsa be most.';

$labels['check_code'] = 'Kód ellenőrzése';
$labels['code_ok'] = 'Helyes kód';
$labels['code_ko'] = 'Hibás kód';

$labels['dont_ask_me_30days'] = 'Ne kérdezze tőlem a kódot a következő 30 napban';

$labels['check_code_to_activate'] = 'A mentéshez kérem olvassa be a QR-kódot és írja be a kapott kétfaktoros kódot.';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Kétfaktoros hitelesítési beállítások sikeresen mentve.';

