<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Attiva';
$labels['twofactor_gauthenticator'] = 'Verifica in due passaggi Google';
$labels['code'] = 'Codice di autenticazione';

$labels['two_step_verification_form'] = 'Verifica in due passaggi';

$labels['secret'] = 'Secret';
$labels['qr_code'] = 'Codice QR';
$labels['msg_infor'] = 'Puoi aggiungere un <i>secret</i> generato con <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) o <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> e utilizzare quello';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Manuale d\'uso</a>';

$labels['show_secret'] = 'Mostra secret';
$labels['hide_secret'] = 'Nascondi secret';
$labels['create_secret'] = 'Crea secret';

$labels['show_qr_code'] = 'Mostra codice QR';
$labels['hide_qr_code'] = 'Nascondi codice QR';

$labels['recovery_codes'] = 'Codici di ripristino';
$labels['show_recovery_codes'] = 'Mostra codici di ripristino';
$labels['hide_recovery_codes'] = 'Nascondi codici di ripristino';

$labels['setup_all_fields'] = 'Configura tutti i campi (richiede un salvataggio)';

$labels['enrollment_dialog_title'] = 'Verifica in due passaggi Google';
$labels['enrollment_dialog_msg'] = '<strong>Codici di verifica due passaggi</strong> sono necessari per sicurezza, prego configurare';

$labels['check_code'] = 'Controlla codice';
$labels['code_ok'] = 'Codice OK';
$labels['code_ko'] = 'Codicec non corretto';

$labels['dont_ask_me_30days'] = 'Non chiedermi più codici per i prossimi 30 giorni su questo computer';

$labels['check_code_to_activate'] = 'Per salvare devi prima verificare il codice';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Configurazione salvata correttamente.';
