<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktivizēt';
$labels['twofactor_gauthenticator'] = '2-Faktoru Autentifikators';
$labels['code'] = 'Autentifikācijas kods';

$labels['two_step_verification_form'] = '2-Faktoru autentifikācijas kods:';

$labels['secret'] = 'Drošības kods';
$labels['qr_code'] = 'QR Kods';
$labels['msg_infor'] = 'Jūs varat noskenēt QR kodu izmantojot <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Apple Store</a>) vai <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> aplikāciju';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Lietotāja rokasgrāmata</a>';

$labels['show_secret'] = 'Parādīt drošības kodu';
$labels['hide_secret'] = 'Paslēpt drošības kodu';
$labels['create_secret'] = 'Izveidot drošības kodu';

$labels['show_qr_code'] = 'Parādīt QR kodu';
$labels['hide_qr_code'] = 'Paslēpt QR kodu';

$labels['recovery_codes'] = 'Atgūšanas kodi';
$labels['show_recovery_codes'] = 'Parādīt atgūšanas kodus';
$labels['hide_recovery_codes'] = 'Paslēpt atgūšanas kodus';

$labels['setup_all_fields'] = 'Automātiski aizpildīt visus laukus';

$labels['enrollment_dialog_title'] = '2-Factor authentication enrollment';
$labels['enrollment_dialog_msg'] = '<strong>2-Faktoru autentifikācijas kodi</strong> nepieciešami, lai uzlabotu drošību.';

$labels['check_code'] = 'Pārbaudīt kodu';
$labels['code_ok'] = 'Pārbaude veiksmīga';
$labels['code_ko'] = 'Nepareizs kods';

$labels['dont_ask_me_30days'] = 'Nejautāt kodu no šīs ierīces nākamās 30 dienas';

$labels['check_code_to_activate'] = 'Lai saglabātu, ievadiet zemāk esošo 2-Faktoru kodu';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = '2-Faktoru autentifikācijas iestatījumi saglabāti.';
