<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Activeren';
$labels['twofactor_gauthenticator'] = '2steps Google verification';
$labels['code'] = 'Google Authenticator Code';
$labels['two_step_verification_form'] = '2-staps verificatie';
$labels['secret'] = 'Secret';
$labels['qr_code'] = 'QR Code';
$labels['msg_infor'] = 'Je kunt een <i>secret</i> genereren via <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> en die hier gebruiken.';
$labels['show_secret'] = 'Secret weergeven';
$labels['hide_secret'] = 'Secret verbergen';
$labels['create_secret'] = 'Secret aanmaken';
$labels['show_qr_code'] = 'QR Code weergeven';
$labels['hide_qr_code'] = 'QR Code verbergen';
$labels['recovery_codes'] = 'Herstelcodes';
$labels['show_recovery_codes'] = 'Herstelcodes weergeven';
$labels['hide_recovery_codes'] = 'Herstelcodes verbergen';
$labels['setup_all_fields'] = 'Alle velden instellen (vereist )';
$labels['enrollment_dialog_title'] = '2-staps verificatie';
$labels['enrollment_dialog_msg'] = '<strong>2-staps verificatiecodes</strong> zijn vereist voor veiligheid, stel ze alstublieft in';
$labels['check_code'] = 'Check code';
$labels['code_ok'] = 'Code correct';
$labels['code_ko'] = 'Code incorrect';
$labels['dont_ask_me_30days'] = 'Vraag me de komende 30 dagen niet opnieuw op deze computer';
$labels['check_code_to_activate'] = 'Om op te slaan, scan alstublieft de QR Code en voer de verificatiecode hieronder in.';
// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Instellingen zijn succesvol opgeslagen.';
?>
