<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktiver';
$labels['twofactor_gauthenticator'] = '2-trinns Google verifikasjon';
$labels['code'] = 'Autentiseringskode';

$labels['two_step_verification_form'] = '2-trinns verifikasjon';
$labels['remember_computer'] = 'Hugs denne datamaskinen';

$labels['secret'] = 'Hemmelegheit';
$labels['qr_code'] = 'QR-kode';
$labels['msg_infor'] = 'You can add a <i>secret</i> generated with <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) or <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> and use that';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">User manual</a>';

$labels['show_secret'] = 'Vis hemmelegheita';
$labels['hide_secret'] = 'Skjul hemmelegheita';
$labels['create_secret'] = 'Ny hemmelegheit';

$labels['show_qr_code'] = 'Vis QR-koden';
$labels['hide_qr_code'] = 'Skjul QR-koden';

$labels['recovery_codes'] = 'Gjenopprettingskodar';
$labels['show_recovery_codes'] = 'Vis gjenopprettingskodane';
$labels['hide_recovery_codes'] = 'Skjul gjenopprettingskodane';

$labels['setup_all_fields'] = 'Setje opp alle felt (trenger å lagre skjermaet)';

$labels['enrollment_dialog_title'] = '2-trinns Google verifikasjon';
$labels['enrollment_dialog_msg'] = 'Du må setje opp <strong>2-trinns verifikasjon kodar</strong> for sikkerheit.';

$labels['check_code'] = 'Sjekk kode';
$labels['code_ok'] = 'God kode';
$labels['code_ko'] = 'Kode feil';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Configuration are saved successfully.';

