<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktywuj';
$labels['twofactor_gauthenticator'] = 'Dwu etapowa autentykacja';
$labels['code'] = 'Google Authenticator Code';

$labels['two_step_verification_form'] = 'Podaj hasło jednorazowe';

$labels['secret'] = 'Tajny klucz';
$labels['qr_code'] = 'Kod QR';
$labels['msg_infor'] = 'Możesz dodać <i>tajny kod</i> wygenerowany przez aplikację <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> i użyć go';

$labels['show_secret'] = 'Pokaż tajny klucz';
$labels['hide_secret'] = 'Ukryj tajny klucz';
$labels['create_secret'] = 'Generuj tajny klucz';

$labels['show_qr_code'] = 'Pokaż Kod QR';
$labels['hide_qr_code'] = 'Ukryj Kod QR';

$labels['recovery_codes'] = 'Hasła jednorazowe';
$labels['show_recovery_codes'] = 'Pokaż hasła jednorazowe';
$labels['hide_recovery_codes'] = 'Ukryj hasła jednorazowe';

$labels['setup_all_fields'] = 'Generuj wszystkie pola (Po weryfikacji kodu kliknij zapisz)';

$labels['enrollment_dialog_title'] = 'Dwu Etapowa Autentykacja';
$labels['enrollment_dialog_msg'] = 'Ze względów bezpieczeństwa konieczne jest skonfigurowanie  i włączenie <strong>dwu etapowej autentykacji</strong>';

$labels['check_code'] = 'Sprawdź Kod';
$labels['code_ok'] = 'Kod OK';
$labels['code_ko'] = 'Błędny kod';

$labels['dont_ask_me_30days'] = 'Nie pytaj ponownie o kod na tym komputerze przez następne 30 dni';

$labels['check_code_to_activate'] = 'Aby zapisać, zeskanuj kod QR i zweryfikuj go przyciskiem Sprawdź Kod';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Konfiguracja zapisana prawidłowo.';

