<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Активировать';
$labels['twofactor_gauthenticator'] = 'Двухэтапная аутентификация';
$labels['code'] = 'Код аутентификации';

$labels['two_step_verification_form'] = 'Двухэтапная Аутентификация';

$labels['secret'] = 'Ключ';
$labels['qr_code'] = 'QR-код';
$labels['msg_infor'] = 'Вы можете добавить <i>ключ</i> сгенерированный <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) или <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> и использовать его';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Руководство пользователя</a>';

$labels['show_secret'] = 'Показать ключ';
$labels['hide_secret'] = 'Скрыть ключ';
$labels['create_secret'] = 'Создать ключ';

$labels['show_qr_code'] = 'Показать QR-код';
$labels['hide_qr_code'] = 'Скрыть QR-код';

$labels['recovery_codes'] = 'Коды восстановления';
$labels['show_recovery_codes'] = 'Показать коды';
$labels['hide_recovery_codes'] = 'Скрыть коды';

$labels['setup_all_fields'] = 'Заполнить все поля (необходимо Сохранить)';

$labels['enrollment_dialog_title'] = 'Двухэтапная Google аутентификация';
$labels['enrollment_dialog_msg'] = '<strong>Коды двухэтапной аутентификации</strong> требуются для безопасности, пожалуйста настройте';

$labels['check_code'] = 'Проверить код';
$labels['code_ok'] = 'Код в порядке';
$labels['code_ko'] = 'Неверный код';

$labels['dont_ask_me_30days'] = 'Не спрашивать коды на этом компьютере 30 дней';

$labels['check_code_to_activate'] = 'Для сохранения, необходимо проверить код';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Настройки успешно сохранены.';

