<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktiverat: ';
$labels['twofactor_gauthenticator'] = 'Tvåstegsverifiering';
$labels['code'] = 'Autentiseringskod';

$labels['two_step_verification_form'] = 'Tvåstegsverifieringskod:';

$labels['secret'] = 'Hemlig nyckel';
$labels['qr_code'] = 'QR-kod';

$labels['msg_infor'] = 'Du kan scanna QR-koden innehållande din hemliga nyckel med en TOTP kompatibel applikation, Typ <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a>';

$labels['show_secret'] = 'Visa hemlig nyckel';
$labels['hide_secret'] = 'Dölj hemlig nyckel';
$labels['create_secret'] = 'Skapa hemlig nyckel';

$labels['show_qr_code'] = 'Visa QR-kod';
$labels['hide_qr_code'] = 'Dölj QR-kod';

$labels['recovery_codes'] = 'Återställningskoder';
$labels['show_recovery_codes'] = 'Visa återställningskoder';
$labels['hide_recovery_codes'] = 'Dölj återställningskoder';

$labels['setup_all_fields'] = 'Fyll i alla fält (Se till att trycka på spara annars går alla ändringar förlorade)';

$labels['enrollment_dialog_title'] = '2-Factor authentication enrollment';
$labels['enrollment_dialog_msg'] = '<strong>2-Factor authentication codes</strong> are required for increased security, please configure them now.';

$labels['check_code'] = 'Kontrollera kod';
$labels['code_ok'] = 'Koden godkänd';
$labels['code_ko'] = 'Inkorrekt kod';

$labels['dont_ask_me_30days'] = 'KOm i håg mig på den här enheten i 30 dagar';

$labels['check_code_to_activate'] = 'KOntrollera kod för att aktivera';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Tvåstegsverifieringsinställningar sparade';

