<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Aktivera';
$labels['twofactor_gauthenticator'] = 'Tvåstegsverifiering';
$labels['code'] = 'Verifieringskod';

$labels['two_step_verification_form'] = 'Tvåstegsverifieringskod:';

$labels['secret'] = 'Hemlig nyckel';
$labels['qr_code'] = 'QR-kod';

$labels['msg_infor'] = 'Du kan scanna QR-koden innehållande din hemliga nyckel med en TOTP kompatibel applikation, typ <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) eller <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a>';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Bruksanvisning</a>';

$labels['show_secret'] = 'Visa hemlig nyckel';
$labels['hide_secret'] = 'Dölj hemlig nyckel';
$labels['create_secret'] = 'Skapa hemlig nyckel';

$labels['show_qr_code'] = 'Visa QR-kod';
$labels['hide_qr_code'] = 'Dölj QR-kod';

$labels['recovery_codes'] = 'Återställningskoder';
$labels['show_recovery_codes'] = 'Visa återställningskoder';
$labels['hide_recovery_codes'] = 'Dölj återställningskoder';

$labels['setup_all_fields'] = 'Fyll i alla fält (se till att trycka på spara annars går alla ändringar förlorade)';

$labels['enrollment_dialog_title'] = 'Konfigurera tvåstegsverifiering';
$labels['enrollment_dialog_msg'] = '<strong>Tvåstegsverifiering</strong> krävs för ökad säkerhet, vänligen konfigurera dem nu.';

$labels['check_code'] = 'Kontrollera kod';
$labels['code_ok'] = 'Koden godkänd';
$labels['code_ko'] = 'Inkorrekt kod';

$labels['dont_ask_me_30days'] = 'Kom ihåg mig på den här enheten i 30 dagar';

$labels['check_code_to_activate'] = 'Kontrollera kod för att aktivera';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Tvåstegsverifieringsinställningar sparade';

