<?php
// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Påslaget: ';
$labels['twofactor_gauthenticator'] = 'Flerstegsverifiering';
$labels['code'] = 'Autentiseringskod';
$labels['two_step_verification_form'] = 'Tvåstegsverifieringskod:';
$labels['secret'] = 'Hemlig nyckel';
$labels['qr_code'] = 'QR-kod';
$labels['msg_infor'] = 'Du kan scanna QR-koden innehållande din hemliga nyckel med en TOTP kompatibel applikation, Typ <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a>';
$labels['show_secret'] = 'Visa nyckel';
$labels['hide_secret'] = 'Dölj nyckel';
$labels['create_secret'] = 'Skapa nyckel';
$labels['show_qr_code'] = 'Visa QR-kod';
$labels['hide_qr_code'] = 'Dölj QR-kod';
$labels['recovery_codes'] = 'Återställningskoder';
$labels['show_recovery_codes'] = 'Visa återställningskoder';
$labels['hide_recovery_codes'] = 'Dölj återställningskoder';
$labels['setup_all_fields'] = 'Fyll i alla fält';
$labels['enrollment_dialog_title'] = '2-Factor authentication enrollment';
$labels['enrollment_dialog_msg'] = '<strong>2-Factor authentication codes</strong> are required for increased security, please configure them now.';
$labels['check_code'] = 'Kontrollera kod';
$labels['code_ok'] = 'Koden godkänd';
$labels['code_ko'] = 'Inkorrekt kod';
$labels['dont_ask_me_30days'] = 'Kom i håg mig i 30 dagar';
$labels['check_code_to_activate'] = 'Kontrollera aktiveringskod';
// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Verifieringsinställningar sparade';
