<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Активувати';
$labels['twofactor_gauthenticator'] = 'Двоетапна аутентифікація';
$labels['code'] = 'Код аутентифікації';

$labels['two_step_verification_form'] = 'Двоетапна аутентифікація';

$labels['secret'] = 'Ключ';
$labels['qr_code'] = 'QR-код';
$labels['msg_infor'] = 'Ви можете відсканувати цей QR-код із двофакторними налаштуваннями за допомогою програми, сумісної з TOTP, наприклад <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a>: <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank">Android</a>, <a href="https://apps.apple.com/app/google-authenticator/id388497605" target="_blank">iOS</a>';
$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Посібник користувача</a>';

$labels['show_secret'] = 'Показати ключ';
$labels['hide_secret'] = 'Сховати ключ';
$labels['create_secret'] = 'Створити ключ';

$labels['new_secret'] = 'Створити НОВИЙ ключ';

$labels['show_qr_code'] = 'Показати QR-код';
$labels['hide_qr_code'] = 'Сховати QR-код';

$labels['recovery_codes'] = 'Коди відновлення';
$labels['remaining_recovery_codes'] = 'Невикористані коди';
$labels['show_recovery_codes'] = 'Показати коди';
$labels['hide_recovery_codes'] = 'Сховати коди';
$labels['new_recovery_codes'] = 'Перегенерувати резервни коди';

$labels['setup_all_fields'] = 'Заповнити всі поля (необхідно Зберегти)';

$labels['enrollment_dialog_title'] = 'Двоетапна Google аутентифікація';
$labels['enrollment_dialog_msg'] = '<strong>Коди двоетапної автентифікації</strong> потрібні для безпеки, будь ласка, налаштуйте';

$labels['check_code'] = 'Перевірити код';
$labels['code_ok'] = 'Код перевірено';
$labels['code_ko'] = 'Код недійсний';

$labels['dont_ask_me_days'] = 'Не запитувати коди на цьому комп&#39;ютері {DAYS} днів';

$labels['check_code_to_activate'] = 'Для збереження, проскануйте QR-код і введіть поточний код нижче.';

$labels['test_passcode'] = 'Перевірте згенерований пароль тут';

$labels['proceed'] = 'Продовжити';


// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Налаштування 2-факторної автентифікації успішно збережено.';

