<?php

// Labels used for different portions of the plugin
$labels = array();
$labels['activate'] = 'Активувати';
$labels['twofactor_gauthenticator'] = 'Двоетапна автентифікація';
$labels['code'] = 'Код автентифікації';

$labels['two_step_verification_form'] = 'Двоетапна Аутентифікація';

$labels['secret'] = 'Ключ';
$labels['qr_code'] = 'QR-код';
$labels['msg_infor'] = 'Ви можете додати <i>ключ</i> згенерований <a href="https://github.com/Skyost/OpenAuthenticator" target="_blank">OpenAuthenticator</a> (<a href="https://play.google.com/store/apps/details?id=app.openauthenticator" target="_blank">Play Store</a> | <a href="https://apps.apple.com/us/app/open-authenticator-by-skyost/id6479272927" target="_blank">Istore</a>) або <a href="https://github.com/google/google-authenticator" target="_blank">google-authenticator</a> та використовувати його';

$labels['msg_help'] = '<a href="https://github.com/alexandregz/twofactor_gauthenticator/tree/master?tab=readme-ov-file#usage" target="_blank">Посібник користувача</a>';

$labels['show_secret'] = 'Показати ключ';
$labels['hide_secret'] = 'Приховати ключ';
$labels['create_secret'] = 'Створити ключ';

$labels['show_qr_code'] = 'Показати QR-код';
$labels['hide_qr_code'] = 'Приховати QR-код';

$labels['recovery_codes'] = 'Коди відновлення';
$labels['show_recovery_codes'] = 'Показати коды';
$labels['hide_recovery_codes'] = 'Приховати коды';

$labels['setup_all_fields'] = 'Заповнити всі поля (необхідно Зберегти)';

$labels['enrollment_dialog_title'] = 'Двоетапна Google автентифікація';
$labels['enrollment_dialog_msg'] = '<strong>Коди двоетапної автентифікації</strong> потрібні для безпеки, будь ласка, налаштуйте';

$labels['check_code'] = 'Перевірити код';
$labels['code_ok'] = 'Код у порядку';
$labels['code_ko'] = 'Невірний код';

$labels['dont_ask_me_30days'] = 'Не питати коди на цьому компютері 30 днів';

$labels['check_code_to_activate'] = 'Для збереження необхідно перевірити код';

// Messages used for the different portions of the plugin
$messages = array();
$messages['successfully_saved'] = 'Налаштування успішно збережено.';

